#!/bin/bash
# Debian 9 and 10 VPS Installer



OvpnDownload_Port='81' # Before changing this value, please read this document. It contains all unsafe ports for Google Chrome Browser, please read from line #23 to line #89: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc

# Server local time
MyVPS_Time='Asia/Kuala_Lumpur'
#############################



 apt-get update
 apt-get upgrade -y
 apt-get install nginx 

 # Creating nginx config for our ovpn config downloads webserver
 cat <<'myNginxC' > /etc/nginx/conf.d/bonveio-ovpn-config.conf
# My OpenVPN Config Download Directory
server {
 listen 0.0.0.0:myNginx;
 server_name localhost;
 root /var/www/openvpn;
 index index.html;
}
myNginxC

 # Setting our nginx config port for .ovpn download site
 sed -i "s|myNginx|$OvpnDownload_Port|g" /etc/nginx/conf.d/bonveio-ovpn-config.conf


 # Creating our root directory for all of our .ovpn configs
#  rm -rf /var/www/openvpn
#  mkdir -p /var/www/openvpn


 # Creating OVPN download site index.html
cat <<'mySiteOvpn' > /var/www/openvpn/index.html
<!DOCTYPE html>
<html lang="en">

<!-- Simple OVPN Download site by Bonveio Abitona -->
<head>
    <meta charset="utf-8" />
    <title>KING MAPUA SERVER</title>
    <meta name="description" content="This site is made only for GVPNHUB CONF's and are NOT FOR SALE" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta name="theme-color" content="#000000" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    </head>
    <body style="background-image: linear-gradient(to right, #6f9ee8, #427bd4, #195bc2)">
        <div class="container justify-content-center>
            <div class="col-md">
                <div class="view" style="margin-top:3em;margin-bottom:3em;">
                        <center>
                            <img class="w3-circle" src="https://gakod.com/sun.png" width="250px" height="250px" class="card-img-top">
                        </center>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><center><b>Ꮐᐯᑭᑎᕼᑌᗷ.com CONF LIST</b></center></h5>
                        <br>
                        <ul class="list-group">

                            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>TCP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small> For EZ/GS Promo with WNP,SNS,FB and IG freebies</small></p><a class="btn btn-outline-success waves-effect btn-sm" href="tcp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>

                            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>UDP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small> For TU Promos</small></p><a class="btn btn-outline-success waves-effect btn-sm" href="udp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>

                            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>SSL <span class="badge light-blue darken-4">Modem</span><br /><small> Without Promo/Noload</small></p><a class="btn btn-outline-success waves-effect btn-sm" href="ssl.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>

                            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>OHP <span class="badge light-blue darken-4">Experimental</span><br /><small> Good for Payload Experiments and Bughost hunting(BETA)</small></p><a class="btn btn-outline-success waves-effect btn-sm" href="ohp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
                            
                            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p> Sample UDP OVPN <span class="badge light-blue darken-4">Experimental</span><br /><small> More faster than TCP. Low latency, fast upload/download speed.</small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://MYDNS/UDPConfig.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
mySiteOvpn
 
 sed -i "s|NGINXPORT|$OvpnDownload_Port|g" /var/www/openvpn/index.html
 sed -i "s|IP-ADDRESS|$IPADDR|g" /var/www/openvpn/index.html

 # Restarting nginx service
 systemctl restart nginx
